### ISSUE TITLE
Add AWS site health monitors (if we can)

### ISSUE THREAD

**Issue by chachasikes** [cagov/odi-engineering#20]

**Comment by chachasikes** [comment]
Moved this issue to `odi-engineering` - about to add a board for issues that don't belong anywhere so we can elevate the need for a home that makes sense.

**Comment by xjensen** [comment]
I'm thinking we should close this issue. 

We need more information about why we would want to implement health checks.

* Do we have any services that routinely go down, for which we don't have monitoring already? In other words, do we have an immediate need? (I can't think of much beyond just pinging the site domains.)
* Or, are we trying to check off a box to make our publishing model more appealing to other departments? If so, is this still a valuable/viable goal for us, given recent organizational restructuring?

In either case, I think we should be more intentional about which services specifically need health checking. Then we could create separate tickets in each case.

@zakiya, what are your thoughts here?

**Comment by zakiya** [comment]
This ties into a discussions that have come up on both cannabis and covid19. We have a solution for uptime monitoring with Google Console that has been implemented for cannabis and innovations.ca.gov. 

The idea of checking for certain elements and/or regular visual regression testing has also come up. I agree that this is something we need to discuss before we throw ourselves into implementation.

[Documentation](https://coda.io/d/Research_dRpeCJqDanr/Health-monitoring-for-all-ca-gov-Design-System-sites_suTI4)

**Comment by zakiya** [comment]
Gonna close this. Other tasks can be opened if necessary
