### ISSUE TITLE
Set up development pipelines for all headless platforms

### ISSUE THREAD

**Issue by chachasikes** [cagov/odi-engineering#34]
Create development publishing pipelines for testing new UI features on their way to production instances.

**Comment by zakiya** [comment]
We have an odi-publishing pipeline now. Though at this point I think we can start thinking of it as a series of repeatable steps rather than one static entity. Assigning this to @aaronhans  since  digital.ca.gov should be the only one left. And @chachasikes for visibility. 

(Also - Maybe we should change the title so the meaning is more scannable during board grooming sessions?)

**Comment by chachasikes** [comment]
@zakiya Happy for better issue name suggestions.

digital.ca.gov is done. (I checked it off above.)

**Comment by aaronhans** [comment]
I created a ticket to optimize the pipeline for digital.ca.gov. The production instance of that site is still hosted on github pages, will move that to S3 as I setup all the staging/test pipelines from the pantheon WP instances

https://github.com/cagov/digital.ca.gov/issues/40

**Comment by aaronhans** [comment]
Great work on this @zakiya!

Recommend closing this ticket now
