### ISSUE TITLE
Research alternatives to Tableau; document the drawbacks

### ISSUE THREAD

**Issue by zakiya** [cagov/odi-engineering#85]
This could also become a blog post eventually

**Comment by aaronhans** [comment]
Here are the pieces related to this we've written so far and not turned into blog posts: Analysis of movement from Tableau -> D3 on covid19.ca.gov's main dashboard which resulted in 90% reduction in time to interactive: https://docs.google.com/document/d/18MboPkCXAqyf2__VORUp3A_u7wTRc8elFeDPsRwvix8/edit

There is a ton of research behind our Tableau switch because that was a big decision. We got amazing support from CDT who got Tableau's high level engineering and accessibility engineering teams on calls with us to try and eke out all the perf and a11y wins we could before we contemplated making a move to other tools. Here are notes from those meetings: https://docs.google.com/document/d/1DSzm-vnyUgA2qroizhSTJD3fKp8tfi4OeuCOuE8xPiQ/edit#

Here are pages we created out of that research that we used in presentations to CDT leadership to get them onboard with our new technical direction: 
- https://teamdocs.covid19.ca.gov/teams/engineering/performance/
- https://teamdocs.covid19.ca.gov/teams/engineering/vs-state-dash/

I think it is important to make a strong general use case for performance. Here is a paragraph with a lot of backup links written for Golden State Stimulus audit:

A lower performance score results in a poorer performance for site visitors. Slower sites have [higher bounce rates](https://www.thinkwithgoogle.com/marketing-strategies/app-and-mobile/mobile-page-speed-new-industry-benchmarks/), [lower visitor conversion rates](https://www.cloudflare.com/en-gb/learning/performance/more/website-performance-conversion-rates/), [lower user satisfaction levels](https://wpostats.com/) and cause [measurable physical stress for visitors](https://www.neuronsinc.com/cases/ericsson).

Thanks for opening this ticket @zakiya

**Comment by zakiya** [comment]
Moved to [Coda](https://coda.io/d/Engineering-wiki_dL_3_CR2bVn/Tableau-or-no_suEnh#_ludLx).
