### ISSUE TITLE
Document Aug 11 covid19 publishing failure

### ISSUE THREAD

**Issue by zakiya** [cagov/odi-engineering#87]
Since our [Slack history](https://cadotgov.slack.com/archives/CVCSH3CR5/p1660237815708209) isn't permanent, please document what happened, troubleshooting steps, and how the issue was resolved.

**Comment by carterm** [comment]
CDT accidentally deleted `fa-cdt-covid19-d-001` on August 10th.  Because the service name had a `-d-` in it, and it was on the `CDT/ODI Development` resource group, they thought it was safe to delete.

Azure has an `Activity log` panel associated with resource groups where `Delete website` activities can be discovered.

Unfortunately, Azure has no way to store site owner/description information in the resource (unlike AWS) so it there is no way to add documentation to discourage accidental deletes.

**Comment by carterm** [comment]
CDT was able to manually recreate the resource, but settings/source connections had to be manually configured.  This site appears to be functioning normally.

**Comment by zakiya** [comment]
Was it moved to a different resource group and/or renamed? I'd like to minimize the chance of it happening again.

**Comment by zakiya** [comment]
@carterm Can you answer the question above?

**Comment by carterm** [comment]
It was not moved.  Still in the CDT/ODI Development resource group.  Renaming and moving might break links/relations.
