### ISSUE TITLE
Responsibly deprecate Gutenberg plug in 

### ISSUE THREAD

**Issue by zakiya** [cagov/odi-engineering#99]
**Current usage**

 site | version | status 
--|--|--
 cannabis | 1.1.7 | active 
 innovation | 1.2.0 | active 
  
 **Deprecation**

- [x]  Update README
- [x] If you have questions about the California Design System, please contact _____
- [x]  [Follow these suggestions](https://medium.com/maintainer-io/how-to-deprecate-a-repository-on-github-8f0ceb9155e)
- [x]  Make each wordpress code instance independent
- [x] Archive repo

**Comment by chachasikes** [comment]
This sounds like a good plan.

A couple of notes to consider - based on my prior experience working on this project:

Because there have been a handful of implementers (people building ca.gov sites) who 
a. might wind up on this site (I have heard of at least a couple), or 
b. have used the code without informing CDT (which was a portion of some state websites) 

A responsible approach could be to include information about who to contact at CDT. It is likely there are changes since we started and a status update (with date), and pointer to CDT would help to direct any traffic and more continuously up-to-date guidance.
